### Get all users
GET http://localhost:8000/user


### Create a user
POST http://localhost:8000/user
Content-Type: application/json

{
    "username": "genesis",
    "password": "1234",
    "role": "SUPERVISOR"
}


### Delete a user
DELETE http://localhost:8000/user/4be3aaca-7a6c-4d32-8ba1-bba397153220