### Get all visitss
GET http://localhost:8000/visits
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkMmI3ZGIyLTQyYTgtNDcyNi04YzY0LTJkNTA4NjlmM2M1ZCIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQyOTg2MjEsImV4cCI6MTY5NDM4NTAyMX0.Bibi4B0aoBflazk1SzcD854uTfxxXkbHiGhE5SKUsko

### Get all visitss with size of pagination and number of page
GET http://localhost:8000/visits?size=2&page=1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkMmI3ZGIyLTQyYTgtNDcyNi04YzY0LTJkNTA4NjlmM2M1ZCIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQyOTg2MjEsImV4cCI6MTY5NDM4NTAyMX0.Bibi4B0aoBflazk1SzcD854uTfxxXkbHiGhE5SKUsko

### Get a visits by id
GET http://localhost:8000/visits/30bb14f1-3fed-4389-8186-9f0160d0bc4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQzMTU2NDYsImV4cCI6MTY5NDQwMjA0Nn0.tXVvNf4Fq4TsvTvLWC0d_x8f0in1oCbNjU0eL9BFn4Y

### Ceate a visits
POST http://localhost:8000/visits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQzMTU2NDYsImV4cCI6MTY5NDQwMjA0Nn0.tXVvNf4Fq4TsvTvLWC0d_x8f0in1oCbNjU0eL9BFn4Y

{
  "date": "2021-09-08T00:00:00.146Z",
  "time": "2000-01-01T15:30:00.146Z",
  "fullName" : "Maria Mercedes" ,
  "idNumber": "0987654324",
  "entryDate": "2021-09-08T22:15:10.146Z",
  "visitReason": "educación",
  "department": "ADMINISTRACION",
  "status": "EN_CURSO",
  "createdById": "2119a3a9-0de8-433a-aa60-8ddbc4f74d3e"
}

### Update a visits
PATCH http://localhost:8000/visits/30bb14f1-3fed-4389-8186-9f0160d0bc44
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQzMDU3MzUsImV4cCI6MTY5NDM5MjEzNX0.A3aN5DTZFMKGsu89LpHG1L1Oa6JmZ2exjkc-ZwAG2O8

{
    "status": "EN_CURSO"
}

### Update a visits
PATCH http://localhost:8000/visits/30bb14f1-3fed-4389-8186-9f0160d0bc44
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQzMDU3MzUsImV4cCI6MTY5NDM5MjEzNX0.A3aN5DTZFMKGsu89LpHG1L1Oa6JmZ2exjkc-ZwAG2O8

{
    "note": "nueva nota"
}

### Delete a visits
DELETE http://localhost:8000/visits/4be3aaca-7a6c-4d32-8ba1-bba397153220