### Get all visitss
GET http://localhost:8000/visits
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQ1MzUwNDIsImV4cCI6MTY5NDYyMTQ0Mn0.YAUTpSk1Rm5WDedfJb6WI-VV8LnloPhczKyqSvj2Pro

### Get all visitss with size of pagination and number of page
GET http://localhost:8000/visits?size=2&page=1
Content-Type: application/xml
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkMmI3ZGIyLTQyYTgtNDcyNi04YzY0LTJkNTA4NjlmM2M1ZCIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQyOTg2MjEsImV4cCI6MTY5NDM4NTAyMX0.Bibi4B0aoBflazk1SzcD854uTfxxXkbHiGhE5SKUsko

### Get a visits by id
GET http://localhost:8000/visits/30bb14f1-3fed-4389-8186-9f0160d0bc4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQzMTU2NDYsImV4cCI6MTY5NDQwMjA0Nn0.tXVvNf4Fq4TsvTvLWC0d_x8f0in1oCbNjU0eL9BFn4Y

### Ceate a visits
POST http://localhost:8000/visits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjN2JiZGYzLWU1NWMtNDA4NS05MjFiLTQ1ZjhhYWZmNmI3NCIsInVzZXJuYW1lIjoidXNlcjIiLCJyb2xlIjoiUkVDRVBDSU9OIiwiaWF0IjoxNjk0NTQwNjM0LCJleHAiOjE2OTQ2MjcwMzR9.701weiNerDDo6VcafF0zJx-WWQffbgsCuZF9yEPQp70

{
  "fullName" : "Maria Mercedes" ,
  "idNumber": "0987654555",
  "entryDate": "2023-09-05T22:56:00.000Z",
  "visitReason": "educación",
  "department": "ADMINISTRACION",
  "status": "EN_CURSO"
}

### Update a visits
PATCH http://localhost:8000/visits/351cbdba-7e27-42b2-8e84-d54aac04f743
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNjN2JiZGYzLWU1NWMtNDA4NS05MjFiLTQ1ZjhhYWZmNmI3NCIsInVzZXJuYW1lIjoidXNlcjIiLCJyb2xlIjoiUkVDRVBDSU9OIiwiaWF0IjoxNjk0NTQwNjM0LCJleHAiOjE2OTQ2MjcwMzR9.701weiNerDDo6VcafF0zJx-WWQffbgsCuZF9yEPQp70

{
    "status": "FINALIZADO"
}

### Update a visits
PATCH http://localhost:8000/visits/30bb14f1-3fed-4389-8186-9f0160d0bc44
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIxMTlhM2E5LTBkZTgtNDMzYS1hYTYwLThkZGJjNGY3NGQzZSIsInVzZXJuYW1lIjoic3RlZXZlbiIsInJvbGUiOiJSRUNFUENJT04iLCJpYXQiOjE2OTQ1MzUwNDIsImV4cCI6MTY5NDYyMTQ0Mn0.YAUTpSk1Rm5WDedfJb6WI-VV8LnloPhczKyqSvj2Pro

{
    "note": "nueva nota"
}

### Delete a visits
DELETE http://localhost:8000/visits/4be3aaca-7a6c-4d32-8ba1-bba397153220